apiVersion: v1
kind: Service
metadata:
  name: zwitscher-board
  labels:
    zwitscher: board
spec:
  # use NodePort here to be able to access the port on each node
  type: NodePort
  ports:
  - port: 8081
  selector:
    zwitscher: board
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zwitscher-board
spec:
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        zwitscher: board
    spec:
      containers:
      - name: zwitscher-board
        image: "qaware-oss-docker-registry.bintray.io/zwitscher/zwitscher-board"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "750m"
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8081
          initialDelaySeconds: 90
          timeoutSeconds: 30
        env:
        - name: EUREKA_HOST
          value: zwitscher-eureka
        - name: JAVA_OPTS
          value: -Xmx196m
