apiVersion: v1
kind: Service
metadata:
  name: zwitscher-monitor
  labels:
    zwitscher: monitor
spec:
  # use NodePort here to be able to access the port on each node
  type: NodePort
  ports:
  - port: 8989
  selector:
    zwitscher: monitor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zwitscher-monitor
spec:
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        zwitscher: monitor
    spec:
      containers:
      - name: zwitscher-monitor
        image: "qaware-oss-docker-registry.bintray.io/zwitscher/zwitscher-monitor:1.1.0"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8989
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8989
          initialDelaySeconds: 120
          timeoutSeconds: 30
        env:
        - name: EUREKA_HOST
          value: zwitscher-eureka
        - name: JAVA_OPTS
          value: -Xmx128m
